version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tungsten-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tungsten

    ports:
      - "5432:5432"

    volumes:
      # run SQL files automatically on first startup
      - ../sql:/docker-entrypoint-initdb.d

    restart: always
